chatbotURL : 'http://localhost:6000/chatbot-prediction/chatagent/'
chatAgentURL : 'http://localhost:5002/chatbot-prediction/'
callbackURL : 'http://localhost:6000/chatbot-prediction/chatagent/'

flaskData : {
    host : '0.0.0.0',
    port : 5001,
    debugFlag : True
}